language: go

go:
  - 1.11.x
  - tip

before_install:
  - ls
  # - go get -t -v ./...

go_import_path: 
  - github.com/axw/gocov/gocov
  - github.com/AlekSi/gocov-xml
  - github.com/jstemmer/go-junit-report
  - github.com/golang/lint/golint


# script:
#   - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
