// Even Fibonacci numbers
// Problem 2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>


using namespace std;


int fibonacci_series(int N){
    int prev_num1 = 0;
    int prev_num2 = 1;
    int sum = 0;
    int cur_num = 0;
    while(cur_num < N){
        cur_num = prev_num1 + prev_num2;
        if( cur_num % 2 == 0){
            sum += cur_num;
        }

        prev_num1 = prev_num2;
        prev_num2 = cur_num;
    }

    return sum;
}

int main(){
    cout << "Fibonacci even sum: " << fibonacci_series(4000000) << endl;
}